sonar.projectKey=sre-ai-ui
sonar.projectName=sre-ai-ui
sonar.host.url=https://sonar.looper.prod.walmartlabs.com

sonar.sources=src
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.exclusions=**/*.html,**/__tests__/**,**/__mocks__/**,node_modules/**,**.config**,**.spec.ts,**.spec.tsx,**.test.ts,**.test.tsx,coverage/**,playwright-report/**,.next/**,public/**

sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
