sonar.projectKey=a2a-health-agent
sonar.projectName=a2a-health-agent
sonar.projectVersion=0.1.0
sonar.host.url=https://sonar.looper.prod.walmartlabs.com

# Source directories
sonar.sources=src
# Test directories
sonar.tests=tests
# Language
sonar.language=py
# Encoding
sonar.sourceEncoding=UTF-8
sonar.scm.enabled=false

# Coverage reports
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest-report.xml

# Exclusions
sonar.exclusions=**/tests/**, **/models/**, **/docs/**, **/exceptions/**, **/interfaces/**,**/__pycache__/**, **/*.pyc,src/agent/**,src/probe_mcp.py,src/main.py,src/main_lite.py
