
sonar.projectKey=intl-ecomm-svcs:maof-dependency-agent
sonar.projectName=intl-ecomm-svcs:maof-dependency-agent
sonar.projectVersion=1
sonar.host.url=https://sonar.looper.prod.walmartlabs.com

# Source directories
sonar.sources=src

sonar.tests=tests
# Language
sonar.language=py
# Encoding
sonar.sourceEncoding=UTF-8
sonar.scm.enabled=false

# Coverage reports
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest-report.xml

# Exclusions
sonar.exclusions=**/tests/**

 sonar.scanner.socketTimeout=120

